### ISSUE TITLE
quest1 exercises that fail on platform

### ISSUE THREAD

**Issue by jotapero** [01-edu/Branch-Blockchain#73]
These exercises fail on the platform with the following error messages:

retrieve-transaction-value:
![image](https://user-images.githubusercontent.com/15161953/212900955-7696a630-8278-4936-9036-cc2e4ac45c5b.png)

send-transaction-to-peer:
![image](https://user-images.githubusercontent.com/15161953/212901028-d73353be-81d5-4924-b9e9-0bc571f1832c.png)

retrieve-transaction-in-out:
![image](https://user-images.githubusercontent.com/15161953/212901087-17cc7ed0-3fe1-44ba-b5d1-0d6181dd9323.png)

**Comment by Xalava** [comment]
- Tests fixed
- The second test depends on the date of the transaction shared by the student
